name: build

on:
  push:
    branches: ["dev"]
    tags:
      - "v*"

jobs:
  build-linux_x64:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: setup env
        run: sudo apt-get install -y libcap-dev libssl-dev libminiupnpc-dev libnatpmp-dev libzstd-dev

      - name: make
        run: |
          mkdir build
          cd build
          cmake .. -DN2N_OPTION_MINIUPNP=ON -DN2N_OPTION_NATPMP=ON -DN2N_OPTION_CAP=ON -DCMAKE_C_FLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
          cmake --build .

      - name: collect files
        run: |
          mv build/edge build/supernode build/n2n-benchmark build/n2n-portfwd ./
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: n2n_linux_x64
          path: |
            edge
            supernode
            n2n-benchmark
            n2n-portfwd
          if-no-files-found: error

  build-linux_aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: setup env
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb\nArchitectures: amd64/' /etc/apt/sources.list.d/ubuntu.sources
          echo '
          Types: deb
          URIs: http://ports.ubuntu.com/
          Suites: '$(lsb_release -cs)' '$(lsb_release -cs)'-updates '$(lsb_release -cs)'-backports '$(lsb_release -cs)'-security
          Components: main restricted universe multiverse
          Architectures: arm64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
          ' | sudo tee /etc/apt/sources.list.d/arm64.sources
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt-get install -y libcap-dev:arm64 libssl-dev:arm64 libminiupnpc-dev:arm64 libnatpmp-dev:arm64 libzstd-dev:arm64

      - name: make
        run: |
          HOST_TRIPLET=aarch64-linux-gnu
          sudo apt-get install -y binutils-$HOST_TRIPLET gcc-$HOST_TRIPLET
          export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=$HOST_TRIPLET-gcc -DN2N_OPTION_MINIUPNP=ON -DN2N_OPTION_NATPMP=ON -DN2N_OPTION_CAP=ON -DCMAKE_C_FLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
          cmake --build .

      - name: collect files
        run: |
          mv build/edge build/supernode build/n2n-benchmark build/n2n-portfwd ./
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: n2n_linux_aarch64
          path: |
            edge
            supernode
            n2n-benchmark
            n2n-portfwd
          if-no-files-found: error

  build-windows_x64:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64 ninja-build

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install Dependencies via vcpkg
        run: |
          ./vcpkg/vcpkg install openssl:x64-mingw-static zstd:x64-mingw-static

      - name: make
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=x64-mingw-static \
            -DCMAKE_SYSTEM_NAME=Windows \
            -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
            -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
            -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
            -DN2N_OPTION_PTHREAD=OFF \
            -DCMAKE_C_FLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY -static"
          cmake --build .

      - name: collect files
        run: |
          mv build/edge.exe build/supernode.exe build/n2n-benchmark.exe build/n2n-portfwd.exe ./
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: n2n_windows_x64
          path: |
            edge.exe
            supernode.exe
            n2n-benchmark.exe
            n2n-portfwd.exe
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs:
      - build-linux_aarch64
      - build-linux_x64
      - build-windows_x64
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
      - name: zip
        run: |
          for i in */; do
          zip -r "${i%/}.zip" "$i"
          done
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
          fail_on_unmatched_files: true
